## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [45]:
import torch
import torch.nn as nn
from collections import OrderedDict

In [46]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))

model1 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 4)),
    ('relu1', nn.ReLU()),
    ('output', nn.Linear(4, 1))
]))

model2 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 4)),
    ('relu1', nn.ReLU()),
    ('hidden2', nn.Linear(4, 4)),
    ('relu2', nn.ReLU()),
    ('output', nn.Linear(4, 1))
]))

model3 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 8)),
    ('relu1', nn.ReLU()),
    ('output', nn.Linear(8, 1))
]))

In [47]:
print("Model 1:\n", model1)
print("\nModel 2:\n", model2)
print("\nModel 3:\n", model3)

Model 1:
 Sequential(
  (hidden1): Linear(in_features=2, out_features=4, bias=True)
  (relu1): ReLU()
  (output): Linear(in_features=4, out_features=1, bias=True)
)

Model 2:
 Sequential(
  (hidden1): Linear(in_features=2, out_features=4, bias=True)
  (relu1): ReLU()
  (hidden2): Linear(in_features=4, out_features=4, bias=True)
  (relu2): ReLU()
  (output): Linear(in_features=4, out_features=1, bias=True)
)

Model 3:
 Sequential(
  (hidden1): Linear(in_features=2, out_features=8, bias=True)
  (relu1): ReLU()
  (output): Linear(in_features=8, out_features=1, bias=True)
)


In [48]:
# your code here
#data_in = torch.tensor( ...

data_in = torch.tensor([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype=torch.float32)
print("\nData Input:\n", data_in)


Data Input:
 tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [49]:
# your code here
# data_target = torch.tensor( ...

data_target = torch.tensor([
    [0],  # 0+0
    [1],  # 0+1
    [1],  # 1+0
    [2]   # 1+1
], dtype=torch.float32)
print("\nData Target:\n", data_target)


Data Target:
 tensor([[0.],
        [1.],
        [1.],
        [2.]])


In [50]:
# your code here
# criterion = 
# optimizer = 
# Train the model

def train_model(model, data_in, data_target, epochs=2000, lr=0.01):
    criterion = nn.MSELoss()                       # Mean Squared Error
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    for epoch in range(epochs):
        optimizer.zero_grad()
        outputs = model(data_in)                   # forward pass
        loss = criterion(outputs, data_target)     # compute loss
        loss.backward()                            # backprop
        optimizer.step()                           # update weights
    return model

model1 = train_model(model1, data_in, data_target)
model2 = train_model(model2, data_in, data_target)
model3 = train_model(model3, data_in, data_target)

In [51]:
# your code here
# visualize the resuts
with torch.no_grad():
    pred1 = model1(data_in)
    pred2 = model2(data_in)
    pred3 = model3(data_in)

print("\nModel 1 Predictions (rounded):", torch.round(pred1).squeeze().tolist())
print("Model 2 Predictions (rounded):", torch.round(pred2).squeeze().tolist())
print("Model 3 Predictions (rounded):", torch.round(pred3).squeeze().tolist())


Model 1 Predictions (rounded): [0.0, 1.0, 1.0, 2.0]
Model 2 Predictions (rounded): [0.0, 1.0, 1.0, 2.0]
Model 3 Predictions (rounded): [0.0, 1.0, 1.0, 2.0]


In [52]:
#check accuracy
acc1 = torch.equal(torch.round(pred1), data_target)
acc2 = torch.equal(torch.round(pred2), data_target)
acc3 = torch.equal(torch.round(pred3), data_target)

print("\nModel 1 reached 100% accuracy:", acc1)
print("Model 2 reached 100% accuracy:", acc2)
print("Model 3 reached 100% accuracy:", acc3)


Model 1 reached 100% accuracy: True
Model 2 reached 100% accuracy: True
Model 3 reached 100% accuracy: True


In [54]:
# your code here
# print model wights
best_model = None
if acc1:
    best_model = model1
elif acc2:
    best_model = model2
elif acc3:
    best_model = model3

if best_model is None:
    print("\nNo model reached 100% accuracy, picking Model 1 by default.\n")
    best_model = model1
else:
    print("\nChoosing the best model that reached 100% accuracy.\n")

for name, param in best_model.named_parameters():
    print(f"{name}:\n{param.data}\n")


Choosing the best model that reached 100% accuracy.

hidden1.weight:
tensor([[ 0.7531,  0.8357],
        [ 0.0212, -0.2866],
        [ 0.4811,  0.2343],
        [-0.2764, -0.2168]])

hidden1.bias:
tensor([ 0.3052, -0.5387,  0.1709,  1.0107])

output.weight:
tensor([[ 0.9880,  0.4863,  0.1843, -0.6050]])

output.bias:
tensor([0.2785])

